owner: sunnypilot
repo: status-page

sites:
  - name: sunnypilot
    url: https://www.sunnypilot.ai
  - name: sunnylink
    url: https://www.sunnylink.ai
  - name: sunnypilot Community Forum
    url: https://community.sunnypilot.ai

status-website:
  cname: status.sunnypilot.ai
  logoUrl: https://avatars.githubusercontent.com/u/129032390?s=200&v=4
  name: sunnypilot
  introTitle: "Welcome to sunnypilot's status page hub"
  introMessage: Below you'll find status information for each of sunnypilot's products and services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

  metaTags:
    # SEO tags
    - name: "description"
      content: "Real-time status updates and incident history for sunnypilot products and services."
    - name: "keywords"
      content: "sunnypilot, sunnylink, community, forum, discourse, status, uptime, downtime, outage, service health"

    # Embed tags
    - property: "og:title"
      content: "sunnypilot Status"
    - property: "og:description"
      content: "Check real-time availability for sunnypilot, sunnylink, and other services."
    - property: "og:image"
      content: "https://avatars.githubusercontent.com/u/129032390?s=200&v=4"
    - property: "og:url"
      content: "https://status.sunnypilot.ai"
