owner: sunnypilot
repo: status-page

sites:
  - name: sunnypilot
    url: https://www.sunnypilot.ai
  - name: sunnylink
    url: https://www.sunnylink.ai

status-website:
  cname: status.sunnypilot.ai
  logoUrl: https://avatars.githubusercontent.com/u/129032390?s=200&v=4
  name: sunnypilot
  introTitle: "Welcome to sunnypilot's status page hub"
  introMessage: Below you'll find status information for each of sunnypilot's products and services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
